
reset-debug-db:
	@../sead_change_control/bin/copy-database --source sead_production_201912 --target sead_production_201912_debug --force
	@scripts/copy-table --host humlabseadserv.srv.its.umu.se --user humlab_admin --source-database bugsdata_20200219 --target-database sead_production_201912 --source-table INDEX --target-schema bugsdata
	@scripts/copy-table --host humlabseadserv.srv.its.umu.se --user humlab_admin --source-database bugsdata_20200219 --target-database sead_production_201912 --source-table TSynonym --target-schema bugsdata

clean:
	@mvn -Dmaven.test.skip=true clean

package:
	@mvn -Dmaven.test.skip=true package

rebuild: clean package
	@echo "Done!"

rebuild-all: clean
	@mvn package
	@echo "Done!"

validate-policy-format:
	@sh ./mvnw -q -Dtest=PolicyFormatValidationTest,RelativeDateMergerFixtureExecutionTest,RelativeAgeManagerFixtureExecutionTest,RelativeDateUpdaterForCalendarFixtureExecutionTest,DatingLabResolverFixtureExecutionTest,RelativeDateMethodManagerFixtureExecutionTest,RelativeDateDatasetUpdaterFixtureExecutionTest,RelativeDateAnalysisEntityFixtureExecutionTest,RelativeDateOutputGraphFixtureExecutionTest,GeochronologyDatasetCreatorFixtureExecutionTest,GeochronologyAnalysisEntityCreatorFixtureExecutionTest,DatingLabCountryResolverFixtureExecutionTest,LabRowConverterFixtureExecutionTest,BibliographyRowConverterFixtureExecutionTest,EcocodeGroupRowConverterFixtureExecutionTest,BugsDefinitionRowConverterFixtureExecutionTest,KochDefinitionRowConverterFixtureExecutionTest,BugsEcocodeRowConverterFixtureExecutionTest,KochEcocodesRowConverterFixtureExecutionTest,BiologyToTextBiologyRowConverterFixtureExecutionTest,KeysTableRowConverterFixtureExecutionTest,SpeciesAssociationRowConverterFixtureExecutionTest,SynonymRowConverterFixtureExecutionTest,PeriodRowConverterFixtureExecutionTest,RdbSystemRowConverterFixtureExecutionTest,MCRSummaryTableRowConverterFixtureExecutionTest,McrNameTableRowConverterFixtureExecutionTest,TaxaSeasonalityBugsTableRowConverterFixtureExecutionTest,BirmBeetleDataRowConverterFixtureExecutionTest,IndexRowConverterFixtureExecutionTest,TaxaSpeciesConverterFixtureExecutionTest,BugsSiteTableConverterFixtureExecutionTest,SiteReferenceBugsTableRowConverterFixtureExecutionTest,CountryRowConverterFixtureExecutionTest,RdbCodeTableRowConverterFixtureExecutionTest,SpeciesDistributionTableRowConverterFixtureExecutionTest,TaxoNotesTableRowConverterFixtureExecutionTest,AnalysisEntityManagerFixtureExecutionTest,DatasetContactUpdaterFixtureExecutionTest,SiteOtherRecordUpdaterFixtureExecutionTest,SiteLocationUpdaterFixtureExecutionTest,SiteLocationBugsTableRowConverterFixtureExecutionTest,ResolverPolicyHarnessTest,ReconciliationPolicyHarnessTest,PostprocessPolicyHarnessTest,RelatedOutputPolicyHarnessTest,SupportingOutputPolicyHarnessTest,OutputPolicyHarnessTest test
	@echo "Policy validation passed"

.PHONY: config
config:
	@cat ./config/application.properties

tools:
	@@sudo apt install mdbtools unixodbc
