-- generated by Jailer 14.2, Fri Feb 10 15:46:09 CET 2023 from roma0050@1020-LT2516

-- Extraction Model:  TSample where T.SampleCODE = 'SAMP000546' (file:/C:/Users/roma0050/AppData/Local/Temp/jailer4838306724498571187/em-15-46-00-982.jm)
-- Source DBMS:       PostgreSQL
-- Target DBMS:       PostgreSQL
-- Database URL:      jdbc:postgresql://humlabseadserv.srv.its.umu.se:5432/bugsdata_20230206
-- Database User:     humlab_admin

-- Exported Rows:     22
--    INDEX                             3
--    TBiblio                           4
--    TCountsheet                       1
--    TDatesMethods                     1
--    TDatesPeriod                      1
--    TFossil                           2
--    TLookupCountsheetContext          1
--    TLookupCountsheetTypes            1
--    TPeriods                          1
--    TSample                           1
--    TSite                             1
--    TSiteOtherProxies                 1
--    TSynonym                          3
--    TTaxoNotes                        1

-- sync
Insert into INDEX(CODE, FAMILY, GENUS, SPECIES, AUTHORITY) values
    ('23.028001499999998', 'STAPHYLINIDAE', 'Eucnecosum', 'brachypterum (grp)', '(Grav.)'),
    ('93.015056999999999', 'CURCULIONIDAE', 'Otiorhynchus', 'nodosus', '(Möll.)'),
    ('40.002102000000001', 'SCIRTIDAE', 'Ptilodactyla', 'exotica', 'Chapin');
Insert into TBiblio(REFERENCE, AUTHOR, TITLE, Notes) values
    ('Bell & Walker (2005)', 'Bell, M. & Walker M.J.C. (1992)', 'Late Quaternary Environmental Change - Physical and Human Perspectives (Second Edition). Longman, Essex.', null),
    ('Bohme 2005', 'Böhme, J. (2005)', 'Die Köfer Mitteleuropas. K. Katalog (Faunistiche Übersicht) (2nd ed.). Spektrum Academic, Munich.', '(revised version of Lucht 1987)'),
    ('Morris 2006', 'Morris, M. (2006)', 'Checklist of beetles of the British Isles, Curculionidae. <www.coleopterist.org.uk/curculionidae-list.htm>.', null),
    ('Strand 1946', 'Strand, A. (1946)', 'Nord Norges Coleoptera. Tromsö Museums Arshefter, Naturhistorisk Avd. Nr. 34, 67(1). (629pp.)', null);
Insert into TDatesMethods(Abbrev, Method, Type, SortOrder) values
    ('GeolPer', 'Geological period', 'Period', 2);
Insert into TLookupCountsheetContext(SheetContext, SortOrder) values
    ('Stratigraphic sequence', 3);
Insert into TLookupCountsheetTypes(CountsheetType, SortOrder) values
    ('Abundances', 1);
Insert into TSite(SiteCODE, SiteName, Region, Country, NGR, LatDD, LongDD, Alt, IDBy, Interp, Specimens) values
    ('SITE000253', 'Håkulls Mosse, Kullaberg', 'Skåne', 'Sweden', null, 56.3, 12.533334, 125.0, 'Lemdahl', 'Kullen Peninsula, see also Björkeröds mosse.', null);
-- sync
Insert into TCountsheet(CountsheetCODE, CountsheetName, SiteCODE, SheetContext, SheetType) values
    ('COUN000144', 'Hakullsmosse_bugsdata.XLS', 'SITE000253', 'Stratigraphic sequence', 'Abundances');
Insert into TPeriods(PeriodCODE, PeriodName, PeriodType, PeriodDesc, PeriodRef, PeriodGeog, Begin, BeginBCAD, End, EndBCAD, YearsType) values
    ('LG', 'Lateglacial', 'Geological', 'Cold period after the last Glaciation. Pollen Zones I-III', 'Bell & Walker (2005)', 'Europe', 13500, 'BP', 10000, 'BP', 'C14');
Insert into TSiteOtherProxies(OtherProxyID, SiteCODE, HasPollen, HasPlantMacro, HasDiatoms, HasChironomids, HasSoilChemistry, HasIsotopes, HasAnimalBones, HasArchaeology, HasMolluscs) values
    (70, 'SITE000253', 1, 0, 0, 0, 0, 0, 0, 0, 0);
Insert into TSynonym(CODE, SynGenus, SynSpecies, SynAuthority, Ref, Notes) values
    ('93.015056999999999', 'Otiorhynchus', 'dubius', '(Ström.)', 'Bohme 2005', null),
    ('93.015056999999999', 'Otiorhynchus', 'maurus', '(Gyllenhal) non (Marsham)', 'Morris 2006', null),
    ('23.028001499999998', 'Arpedium', null, null, 'Strand 1946', null);
-- Insert into TSynonym(CODE, SynGenus, SynSpecies, SynAuthority, Ref, Notes, SynonymCODE) values
--     ('93.015056999999999', 'Otiorhynchus', 'dubius', '(Ström.)', 'Bohme 2005', null, 1404),
--     ('93.015056999999999', 'Otiorhynchus', 'maurus', '(Gyllenhal) non (Marsham)', 'Morris 2006', null, 3930),
--     ('23.028001499999998', 'Arpedium', null, null, 'Strand 1946', null, 6062);
Insert into TTaxoNotes(CODE, Ref, Data) values
    ('40.002102000000001', 'Bohme 2005', 'Genus not listed.');
-- sync
Insert into TSample(SampleCODE, SiteCODE, X, Y, ZorDepthTop, ZorDepthBot, RefNrContext, CountsheetCODE) values
    ('SAMP000546', 'SITE000253', null, null, null, null, 'B8:6/6', 'COUN000144');
-- sync
Insert into TDatesPeriod(PeriodDateCODE, SampleCODE, Uncertainty, PeriodCODE, DatingMethod, Notes) values
    ('PERI005175', 'SAMP000546', null, 'LG', 'GeolPer', null);
Insert into TFossil(FossilBugsCODE, CODE, SampleCODE, Abundance) values
    ('FOSS014299', '93.015056999999999', 'SAMP000546', 3),
    ('FOSS144182', '23.028001499999998', 'SAMP000546', 30);

-- Vital times
--   Collecting: 00:00:01.9
--   Exporting:  00:00:00.4
--   Total:      00:00:02.4
